package com.mpp.aedialsworks.smoke;
import java.util.*;
import appeng.api.config.Actionable;
import appeng.api.networking.*;
import appeng.api.networking.security.IActionSource;
import appeng.api.parts.PartHelper;
import appeng.api.stacks.*;
import appeng.api.storage.StorageCells;
import appeng.core.definitions.*;
import appeng.blockentity.storage.DriveBlockEntity;
import appeng.blockentity.grid.AENetworkBlockEntity;
import com.mpp.aedialsworks.common.registry.*;
import com.mpp.aedialsworks.common.recipe.*;
import com.mpp.aedialsworks.cells.*;
import com.mpp.aedialsworks.cells.api.*;
import com.mpp.aedialsworks.cells.cell.*;
import com.mpp.aedialsworks.cells.cell.compacting.*;
import com.mpp.aedialsworks.cells.integration.ae2.*;
import com.mpp.aedialsworks.cells.interfaceblock.*;
import com.mpp.aedialsworks.cells.subnetproxy.*;
import net.minecraft.core.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.world.item.*;
import net.minecraft.world.item.crafting.*;
import net.minecraft.world.level.material.Fluids;
import net.minecraftforge.gametest.*;
import net.minecraftforge.common.capabilities.ForgeCapabilities;
import net.minecraftforge.fluids.FluidStack;
import net.minecraftforge.fluids.capability.IFluidHandler;
@GameTestHolder("aedialsworks") @PrefixGameTestTemplate(false)
public final class P3GameTests {
    private static final IActionSource SOURCE=IActionSource.empty();
    private static final AEItemKey IRON=AEItemKey.of(Items.IRON_INGOT);
    private static final AEFluidKey WATER=AEFluidKey.of(Fluids.WATER);
    private static long count(appeng.api.storage.MEStorage storage,AEKey key){var all=new KeyCounter();storage.getAvailableStacks(all);return all.get(key);}
    private static void network(GameTestHelper h,MachineKind kind){h.setBlock(1,1,1,AWCells.BLOCKS.get(kind).get());h.setBlock(2,1,1,AEBlocks.DRIVE.block());h.setBlock(2,0,1,AEBlocks.CREATIVE_ENERGY_CELL.block());var drive=(DriveBlockEntity)h.getBlockEntity(new BlockPos(2,1,1));drive.getInternalInventory().setItemDirect(0,AEItems.ITEM_CELL_64K.stack());drive.getInternalInventory().setItemDirect(1,AEItems.FLUID_CELL_64K.stack());h.runAfterDelay(25,()->{var main=machine(h);for(var pos:List.of(new BlockPos(2,1,1),new BlockPos(2,0,1))){var b=(appeng.me.helpers.IGridConnectedBlockEntity)h.getBlockEntity(pos);if(main.getMainNode().getGrid()!=b.getMainNode().getGrid())GridHelper.createConnection(main.getMainNode().getNode(),b.getMainNode().getNode());}});}
    private static CellsBlockEntity machine(GameTestHelper h){return (CellsBlockEntity)h.getBlockEntity(new BlockPos(1,1,1));}
    @GameTest(template="empty") public static void allTierRecipesCellHandlersAndLongAccounting(GameTestHelper h){
        h.assertTrue(AWCells.CELLS.size()==48&&AWCells.COMPONENTS.size()==45&&AWCells.PARTS.size()==10&&AWCells.BLOCKS.size()==9&&AWCells.MATERIALS.size()==22,"Complete registry matrix");
        for(var entry:AWCells.CELLS.values()){
            var stack=new ItemStack(entry.get());var item=entry.get();h.assertTrue(stack.getMaxStackSize()==1&&StorageCells.isCellHandled(stack),"Stack limit and handler "+entry.getId());
            if(item.family.creative()){item.getConfigInventory(stack).setStack(0,new GenericStack(item.family.fluid?WATER:IRON,1));var state=CellHandler.open(stack,null);h.assertTrue(state.extract(item.family.fluid?WATER:IRON,1L<<42,Actionable.MODULATE,SOURCE)==1L<<42,"Creative long extraction");continue;}
            if(item.family==CellFamily.CONFIGURABLE)continue;
            boolean recipe=h.getLevel().getRecipeManager().getRecipes().stream().anyMatch(r->r.getResultItem(h.getLevel().registryAccess()).is(item));h.assertTrue(recipe,"Survival cell recipe "+entry.getId());
            var state=StorageCells.getCellInventory(stack,null);var key=item.family.fluid?WATER:IRON;long requested=item.family.highDensity?1L<<33:81;var before=stack.copy();h.assertTrue(state.insert(key,requested,Actionable.SIMULATE,SOURCE)==requested,"Simulation capacity "+entry.getId());h.assertTrue(ItemStack.matches(before,stack),"Simulation leaves NBT unchanged");
            h.assertTrue(state.insert(key,requested,Actionable.MODULATE,SOURCE)==requested,"Insert "+entry.getId());state.persist();var reopened=StorageCells.getCellInventory(stack.copy(),null);h.assertTrue(reopened.extract(key,requested,Actionable.MODULATE,SOURCE)==requested,"Exact persisted extraction "+entry.getId());
        }
        for(var recipe:h.getLevel().getRecipeManager().getRecipes())if(recipe.getId().getNamespace().equals("aedialsworks"))
            for(var ingredient:recipe.getIngredients())if(!ingredient.isEmpty())h.assertTrue(ingredient.getItems().length>0,"Resolvable recipe ingredient "+recipe.getId());
        h.succeed();
    }
    @GameTest(template="empty") public static void partitionCompactionUpgradeAndRemainderConservation(GameTestHelper h){
        var stack=new ItemStack(AWCells.cell(CellFamily.COMPACTING,CellTier.K1).get());var item=(TieredCellItem)stack.getItem();item.getConfigInventory(stack).setStack(0,new GenericStack(IRON,1));
        var cell=(CompactingCellState)CellHandler.open(stack,null);h.assertTrue(cell.chain()==null,"Unbound empty pool");h.assertTrue(cell.insert(AEItemKey.of(Items.IRON_BLOCK),11,Actionable.MODULATE,SOURCE)==11,"Actual 3x3 reversible recipe");h.assertTrue(cell.extract(IRON,98,Actionable.MODULATE,SOURCE)==98,"Decompress exactly");h.assertTrue(cell.extract(AEItemKey.of(Items.IRON_NUGGET),9,Actionable.MODULATE,SOURCE)==9&&cell.storedUnits()==0,"Residual low denomination preserved");
        h.assertTrue(cell.insert(AEItemKey.of(Items.DIRT),1,Actionable.MODULATE,SOURCE)==0,"Partition rejects unrelated item");cell.insert(IRON,9,Actionable.MODULATE,SOURCE);item.getConfigInventory(stack).setStack(0,new GenericStack(AEItemKey.of(Items.GOLD_INGOT),1));cell= (CompactingCellState)CellHandler.open(stack,null);h.assertTrue(cell.insert(IRON,1,Actionable.MODULATE,SOURCE)==0&&cell.extract(IRON,9,Actionable.MODULATE,SOURCE)==9,"Repartition blocks new input but preserves recovery");
        var dense=new ItemStack(AWCells.cell(CellFamily.HD_ITEM,CellTier.K1).get());var d=(TieredCellItem)dense.getItem();d.getConfigInventory(dense).setStack(0,new GenericStack(IRON,1));var state=CellHandler.open(dense,null);h.assertTrue(state.insert(AEItemKey.of(Items.DIRT),100,Actionable.SIMULATE,SOURCE)==0,"Dense partition");d.getUpgrades(dense).setItemDirect(0,AEItems.INVERTER_CARD.stack());state=CellHandler.open(dense,null);h.assertTrue(state.insert(IRON,1,Actionable.SIMULATE,SOURCE)==0&&state.insert(AEItemKey.of(Items.DIRT),1,Actionable.SIMULATE,SOURCE)==1,"Inverse card");h.succeed();
    }
    @GameTest(template="empty") public static void componentSwapAssemblyAndRecipeTypes(GameTestHelper h){
        var blank=new ItemStack(AWCells.CELLS.get("configurable_cell").get());var component=new ItemStack(AWCells.component(CellFamily.HD_FLUID,CellTier.K1).get());var fluid=CellComponentRecipe.replaced(blank,component);h.assertTrue(!fluid.isEmpty(),"Configurable assembly");var state=CellHandler.open(fluid,null);h.assertTrue(state.insert(WATER,1L<<34,Actionable.MODULATE,SOURCE)==1L<<34,"Component selects fluid and long capacity");
        var expanded=CellComponentRecipe.replaced(fluid,new ItemStack(AWCells.component(CellFamily.HD_FLUID,CellTier.K4).get()));h.assertTrue(!expanded.isEmpty()&&count(CellHandler.open(expanded,null),WATER)==1L<<34,"Filled component swap preserves contents");h.assertTrue(CellComponentRecipe.replaced(fluid,new ItemStack(AWCells.component(CellFamily.HD_ITEM,CellTier.K4).get())).isEmpty(),"Channel-changing swap rejected when filled");
        var huge=new ItemStack(AWCells.cell(CellFamily.HD_ITEM,CellTier.G1).get());CellHandler.open(huge,null).insert(IRON,1L<<55,Actionable.MODULATE,SOURCE);h.assertTrue(CellComponentRecipe.replaced(huge,new ItemStack(AWCells.component(CellFamily.HD_ITEM,CellTier.K1).get())).isEmpty(),"Unsafe shrink rejected");
        long inscriber=h.getLevel().getRecipeManager().getRecipes().stream().filter(x->x.getId().getNamespace().equals("aedialsworks")&&x.getId().getPath().startsWith("cells/inscriber/")).count();h.assertTrue(inscriber==6,"Six real inscriber recipes loaded");h.succeed();
    }
    private static void interfaceTest(GameTestHelper h,MachineKind kind){network(h,kind);final CellsPart[] part={null};
        h.runAfterDelay(30,()->{part[0]=PartHelper.setPart(h.getLevel(),h.absolutePos(new BlockPos(1,1,3)),Direction.NORTH,h.makeMockPlayer(),AWCells.PARTS.get(kind).get());});
        h.runAfterDelay(55,()->{GridHelper.createConnection(machine(h).getMainNode().getNode(),part[0].getGridNode());});
        h.runAfterDelay(80,()->{var storage=machine(h).getMainNode().getGrid().getStorageService().getInventory();storage.insert(IRON,10000,Actionable.MODULATE,SOURCE);storage.insert(WATER,100000,Actionable.MODULATE,SOURCE);
            for(CellsHost host:List.of(machine(h),part[0])){var logic=(InterfaceLogic)host.cellsLogic();for(int u=0;u<4;u++)logic.upgrades.setItemDirect(u,AEItems.CAPACITY_CARD.stack());h.assertTrue(logic.pages()==5,"Capacity cards open all five pages");
                for(var port:logic.ports){AEKey key=port.fluid?WATER:IRON;port.filters[179]=key;port.limits[179]=port.fluid?4000:32;if(!port.output)h.assertTrue(port.insert(179,key,port.fluid?2000:16,false,false)>0,"Last-page import buffer");}
            }});
        h.runAfterDelay(145,()->{for(CellsHost host:List.of(machine(h),part[0])){var logic=(InterfaceLogic)host.cellsLogic();h.assertTrue(logic.active(),"Real grid active");for(var port:logic.ports)h.assertTrue(port.amounts[179]==(port.output?(port.fluid?4000:32):0),"Polling last page "+kind+" "+port.fluid+" "+port.output);
            var saved=logic.save();var copy=AWCells.PARTS.get(kind).get().createPart();copy.logic.load(saved);for(int i=0;i<logic.ports.size();i++)h.assertTrue(((InterfaceLogic)copy.logic).ports.get(i).amounts[179]==logic.ports.get(i).amounts[179],"Buffers reload exactly");
            var card=logic.exportData(appeng.util.SettingsFrom.MEMORY_CARD);h.assertFalse(card.contains("buffers")||card.contains("upgrades"),"Settings cannot duplicate inventory");
        }h.succeed();});
    }
    @GameTest(template="empty",timeoutTicks=200) public static void itemImportBlockAndPart(GameTestHelper h){interfaceTest(h,MachineKind.IMPORT);}
    @GameTest(template="empty",timeoutTicks=200) public static void itemExportBlockAndPart(GameTestHelper h){interfaceTest(h,MachineKind.EXPORT);}
    @GameTest(template="empty",timeoutTicks=200) public static void fluidImportBlockAndPart(GameTestHelper h){interfaceTest(h,MachineKind.FLUID_IMPORT);}
    @GameTest(template="empty",timeoutTicks=200) public static void fluidExportBlockAndPart(GameTestHelper h){interfaceTest(h,MachineKind.FLUID_EXPORT);}
    @GameTest(template="empty",timeoutTicks=200) public static void combinedImportBlockAndPart(GameTestHelper h){interfaceTest(h,MachineKind.COMBINED_IMPORT);}
    @GameTest(template="empty",timeoutTicks=200) public static void combinedExportBlockAndPart(GameTestHelper h){interfaceTest(h,MachineKind.COMBINED_EXPORT);}
    @GameTest(template="empty",timeoutTicks=200) public static void itemIoBlockAndPart(GameTestHelper h){interfaceTest(h,MachineKind.ITEM_IO);}
    @GameTest(template="empty",timeoutTicks=200) public static void fluidIoBlockAndPart(GameTestHelper h){interfaceTest(h,MachineKind.FLUID_IO);}

    @GameTest(template="empty",timeoutTicks=220) public static void proxyFilteredIsolationInsertionAndSameGridGuard(GameTestHelper h){
        h.setBlock(1,1,1,AEBlocks.DRIVE.block());h.setBlock(1,0,1,AEBlocks.CREATIVE_ENERGY_CELL.block());h.setBlock(4,0,1,AEBlocks.CREATIVE_ENERGY_CELL.block());
        var drive=(DriveBlockEntity)h.getBlockEntity(new BlockPos(1,1,1));drive.getInternalInventory().setItemDirect(0,AEItems.ITEM_CELL_64K.stack());
        var back=PartHelper.setPart(h.getLevel(),h.absolutePos(new BlockPos(2,1,1)),Direction.EAST,h.makeMockPlayer(),AWCells.PARTS.get(MachineKind.PROXY_BACK).get());
        var front=PartHelper.setPart(h.getLevel(),h.absolutePos(new BlockPos(3,1,1)),Direction.WEST,h.makeMockPlayer(),AWCells.PARTS.get(MachineKind.PROXY_FRONT).get());
        h.runAfterDelay(30,()->{var power=(appeng.me.helpers.IGridConnectedBlockEntity)h.getBlockEntity(new BlockPos(4,0,1));if(back.getGridNode().getGrid()!=drive.getMainNode().getGrid())GridHelper.createConnection(back.getGridNode(),drive.getMainNode().getNode());GridHelper.createConnection(front.getGridNode(),power.getMainNode().getNode());});
        h.runAfterDelay(90,()->{var proxy=(ProxyLogic)front.logic;var origin=drive.getMainNode().getGrid().getStorageService().getInventory();origin.insert(IRON,120,Actionable.MODULATE,SOURCE);origin.insert(AEItemKey.of(Items.GOLD_INGOT),80,Actionable.MODULATE,SOURCE);front.logic.filters.setStack(0,new GenericStack(IRON,1));h.assertTrue(proxy.guardStatus().equals("READY"),"Paired independently powered networks: "+proxy.guardStatus());
            h.assertTrue(count(proxy.storageView(),IRON)==120&&count(proxy.storageView(),AEItemKey.of(Items.GOLD_INGOT))==0,"Filtered physical storage view");h.assertTrue(proxy.storageView().extract(IRON,20,Actionable.MODULATE,SOURCE)==20&&count(origin,IRON)==100,"Read-through extraction");h.assertTrue(proxy.storageView().insert(IRON,7,Actionable.MODULATE,SOURCE)==0,"Insertion disabled by default");front.logic.upgrades.setItemDirect(0,new ItemStack(AWCells.UPGRADES.get("insertion_card").get()));h.assertTrue(proxy.storageView().insert(IRON,7,Actionable.MODULATE,SOURCE)==7&&count(origin,IRON)==107,"Insertion card writes origin exactly once");
            front.logic.inverse=true;h.assertTrue(count(proxy.storageView(),IRON)==0&&count(proxy.storageView(),AEItemKey.of(Items.GOLD_INGOT))==80,"Inverse filter");front.logic.inverse=false;
            var scanner=new com.mpp.aedialsworks.cellterminal.integration.ae2.Ae2SubnetScanner();h.assertTrue(scanner.connections(front.getGridNode().getGrid()).stream().anyMatch(l->l.to()==back.getGridNode().getGrid()),"Cell Terminal discovers proxy subnet");
            try(var hop=ProxyGuard.Hop.enter()){h.assertTrue(count(proxy.storageView(),IRON)==0&&proxy.storageView().extract(IRON,1,Actionable.MODULATE,SOURCE)==0&&proxy.storageView().insert(IRON,1,Actionable.MODULATE,SOURCE)==0,"Nested listing/read/write blocked");}
            GridHelper.createConnection(front.getGridNode(),back.getGridNode());});
        h.runAfterDelay(150,()->{var proxy=(ProxyLogic)front.logic;h.assertTrue(proxy.guardStatus().equals("SAME_GRID")&&count(proxy.storageView(),IRON)==0,"Same-grid protection after topology change");h.succeed();});
    }
    @GameTest(template="empty",timeoutTicks=600) public static void compactingExposerCompletesRealCpuJob(GameTestHelper h){
        network(h,MachineKind.EXPOSER);h.setBlock(3,1,1,AEBlocks.CRAFTING_STORAGE_1K.block());h.setBlock(3,1,3,AWBlocks.BETTER_LEVEL_MAINTAINER.get());
        h.runAfterDelay(40,()->{var node=machine(h).getMainNode().getNode();for(var pos:List.of(new BlockPos(3,1,1),new BlockPos(3,1,3))){var be=(appeng.me.helpers.IGridConnectedBlockEntity)h.getBlockEntity(pos);if(be.getMainNode().getGrid()!=node.getGrid())GridHelper.createConnection(node,be.getMainNode().getNode());}});
        h.runAfterDelay(85,()->{var be=machine(h);be.cellsLogic().filters.setStack(0,new GenericStack(IRON,1));be.getMainNode().getGrid().getStorageService().getInventory().insert(IRON,18,Actionable.MODULATE,SOURCE);var maintainer=(com.mpp.aedialsworks.powertools.integration.ae2.PowerBlockEntity)h.getBlockEntity(new BlockPos(3,1,3));var logic=(com.mpp.aedialsworks.powertools.maintainer.MaintainerLogic)maintainer.logic();logic.entries[0].key=AEItemKey.of(Items.IRON_BLOCK);logic.entries[0].threshold=2;logic.batch[0]=2;});
        h.succeedWhen(()->{h.assertTrue(h.getTick()>120,"Wait for native CPU");var storage=machine(h).getMainNode().getGrid().getStorageService().getInventory();h.assertTrue(count(storage,AEItemKey.of(Items.IRON_BLOCK))==2&&count(storage,IRON)==0,"Real CPU consumes exactly 18 ingots and returns two blocks");var logic=(com.mpp.aedialsworks.cells.pattern.CompactingPatternLogic)machine(h).cellsLogic();h.assertFalse(logic.isBusy(),"Pending output drained");});
    }
    @GameTest(template="empty") public static void cellMenuSessionLockAndCraftingRemainder(GameTestHelper h){
        var player=net.minecraftforge.common.util.FakePlayerFactory.get(h.getLevel(),new com.mojang.authlib.GameProfile(UUID.randomUUID(),"P3Security"));player.setGameMode(net.minecraft.world.level.GameType.SURVIVAL);var stack=new ItemStack(AWCells.cell(CellFamily.HD_ITEM,CellTier.K1).get());player.getInventory().setItem(0,stack);var session=UUID.randomUUID();var menu=new com.mpp.aedialsworks.cells.menu.CellConfigurationMenu(45,player.getInventory(),0,session);player.containerMenu=menu;
        var n=new CompoundTag();n.putUUID("session",UUID.randomUUID());n.putInt("slot",0);n.put("key",IRON.toTagGeneric());menu.receiveClientAction(player,com.mpp.aedialsworks.common.util.AWIds.id("cell_filter"),n);h.assertTrue(((TieredCellItem)stack.getItem()).getConfigInventory(stack).keySet().isEmpty(),"Stale menu nonce rejected");n.putUUID("session",session);menu.receiveClientAction(player,com.mpp.aedialsworks.common.util.AWIds.id("cell_filter"),n);h.assertTrue(((TieredCellItem)stack.getItem()).getConfigInventory(stack).getKey(0).equals(IRON),"Authorized partition change");
        var hotbar=menu.getSlots(appeng.menu.SlotSemantics.PLAYER_HOTBAR).get(0);menu.clicked(hotbar.index,0,net.minecraft.world.inventory.ClickType.PICKUP,player);h.assertTrue(menu.getCarried().isEmpty()&&player.getInventory().getItem(0)==stack,"Held cell cannot be extracted through native menu");player.getInventory().setItem(0,stack.copy());h.assertFalse(menu.stillValid(player),"Replacement closes stale menu");player.containerMenu=player.inventoryMenu;
        var frame=new net.minecraft.world.inventory.TransientCraftingContainer(new net.minecraft.world.inventory.AbstractContainerMenu(null,0){public ItemStack quickMoveStack(net.minecraft.world.entity.player.Player p,int i){return ItemStack.EMPTY;}public boolean stillValid(net.minecraft.world.entity.player.Player p){return false;}},2,2);frame.setItem(0,stack);frame.setItem(1,new ItemStack(AWCells.component(CellFamily.HD_ITEM,CellTier.K4).get()));var recipe=new CellComponentRecipe(com.mpp.aedialsworks.common.util.AWIds.id("test"),CraftingBookCategory.MISC);h.assertTrue(recipe.matches(frame,h.getLevel())&&recipe.getRemainingItems(frame).get(0).is(AWCells.component(CellFamily.HD_ITEM,CellTier.K1).get()),"Old component returned to crafting grid exactly once");h.succeed();
    }
    private static net.minecraft.world.inventory.CraftingContainer frame(){return new net.minecraft.world.inventory.TransientCraftingContainer(new net.minecraft.world.inventory.AbstractContainerMenu(null,0){public ItemStack quickMoveStack(net.minecraft.world.entity.player.Player p,int i){return ItemStack.EMPTY;}public boolean stillValid(net.minecraft.world.entity.player.Player p){return false;}},3,3);}
    @GameTest(template="empty") public static void nativeChestDriveAndWorkbenchRejectStackedCells(GameTestHelper h){
        h.setBlock(1,1,1,AEBlocks.CHEST.block());h.setBlock(2,1,1,AEBlocks.DRIVE.block());h.setBlock(3,1,1,AEBlocks.CELL_WORKBENCH.block());
        var chest=(appeng.blockentity.storage.ChestBlockEntity)h.getBlockEntity(new BlockPos(1,1,1));var drive=(DriveBlockEntity)h.getBlockEntity(new BlockPos(2,1,1));var workbench=(appeng.blockentity.misc.CellWorkbenchBlockEntity)h.getBlockEntity(new BlockPos(3,1,1));
        h.runAfterDelay(25,()->{for(var item:AWCells.CELLS.values()){var stack=new ItemStack(item.get());chest.setCell(stack.copy());chest.getCellStatus(0);drive.getInternalInventory().setItemDirect(0,stack.copy());h.assertTrue(chest.getOriginalCellInventory(0)!=null&&drive.getCellInventory(0)!=null,"Native chest/drive recognize "+item.getId());}
        chest.setCell(ItemStack.EMPTY);var stack=new ItemStack(AWCells.cell(CellFamily.HD_ITEM,CellTier.K1).get(),64);var inventory=workbench.getSubInventory(appeng.api.inventories.ISegmentedInventory.CELLS);var rest=inventory.insertItem(0,stack,false);h.assertTrue(rest.getCount()==63&&inventory.getStackInSlot(0).getCount()==1,"Workbench admits only one cell");h.assertTrue(workbench.getCell()!=null,"Workbench recognizes partition capability");h.assertTrue(CellHandler.open(stack,null)==null,"Forged stacked cells cannot open storage");
        var chestRest=chest.getInternalInventory().insertItem(1,stack,false);h.assertTrue(chestRest.getCount()>=63,"Chest never consumes stacked cells");h.succeed();});
    }
    @GameTest(template="empty") public static void vanillaComponentsUpgradedSwapsAndOverflowConservation(GameTestHelper h){
        var nativeComponent=new ItemStack(net.minecraft.core.registries.BuiltInRegistries.ITEM.get(new net.minecraft.resources.ResourceLocation("ae2","cell_component_1k")));
        var result=CellComponentRecipe.replaced(new ItemStack(AWCells.CELLS.get("configurable_cell").get()),nativeComponent);h.assertFalse(result.isEmpty(),"Native AE2 component assembly");h.assertTrue(CellHandler.open(result,null).totalBytes()==1024,"Native component has ordinary capacity");
        var cell=new ItemStack(AWCells.cell(CellFamily.HD_ITEM,CellTier.K1).get());var item=(TieredCellItem)cell.getItem();item.getUpgrades(cell).setItemDirect(0,new ItemStack(AWCells.UPGRADES.get("overflow_card").get()));CellHandler.open(cell,null).insert(IRON,1L<<30,Actionable.MODULATE,SOURCE);
        var swapped=CellComponentRecipe.replaced(cell,new ItemStack(AWCells.component(CellFamily.HD_ITEM,CellTier.K4).get()));h.assertTrue(!swapped.isEmpty()&&count(CellHandler.open(swapped,null),IRON)==1L<<30,"Upgraded filled expansion retains contents and upgrade");
        h.assertTrue(CellComponentRecipe.replaced(cell,new ItemStack(AWCells.component(CellFamily.COMPACTING,CellTier.K1).get())).isEmpty(),"Overflow card cannot void contents during conversion");h.succeed();
    }
    @GameTest(template="empty") public static void memoryCardsExcludeInventoryAndOptionallyPreserveFilters(GameTestHelper h){
        h.setBlock(1,1,1,AWCells.BLOCKS.get(MachineKind.COMBINED_IMPORT).get());var logic=(InterfaceLogic)machine(h).cellsLogic();var player=net.minecraftforge.common.util.FakePlayerFactory.get(h.getLevel(),new com.mojang.authlib.GameProfile(UUID.randomUUID(),"P3Memory"));player.setGameMode(net.minecraft.world.level.GameType.SURVIVAL);player.setPos(h.absolutePos(new BlockPos(1,1,1)).getX(),h.absolutePos(new BlockPos(1,1,1)).getY(),h.absolutePos(new BlockPos(1,1,1)).getZ());player.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,AEItems.MEMORY_CARD.stack());
        logic.polling=13;logic.ports.get(0).filters[0]=IRON;logic.ports.get(0).amounts[0]=21;logic.ports.get(0).keys[0]=IRON;player.setShiftKeyDown(true);h.assertTrue(com.mpp.aedialsworks.cells.network.CellsMemoryCards.interact(player,machine(h).cellsPos(),null,net.minecraft.world.InteractionHand.MAIN_HAND,false),"Server memory card save: build="+player.mayBuild()+" interact="+h.getLevel().mayInteract(player,machine(h).cellsPos())+" host="+machine(h).canUseCells(player));logic.polling=2;logic.ports.get(0).filters[0]=AEItemKey.of(Items.GOLD_INGOT);player.setShiftKeyDown(false);com.mpp.aedialsworks.cells.network.CellsMemoryCards.interact(player,machine(h).cellsPos(),null,net.minecraft.world.InteractionHand.MAIN_HAND,false);h.assertTrue(logic.polling==13&&logic.ports.get(0).filters[0].equals(AEItemKey.of(Items.GOLD_INGOT))&&logic.ports.get(0).amounts[0]==21,"Default preserves destination filters and inventory");
        player.setShiftKeyDown(true);com.mpp.aedialsworks.cells.network.CellsMemoryCards.interact(player,machine(h).cellsPos(),null,net.minecraft.world.InteractionHand.MAIN_HAND,true);logic.ports.get(0).filters[0]=IRON;player.setShiftKeyDown(false);com.mpp.aedialsworks.cells.network.CellsMemoryCards.interact(player,machine(h).cellsPos(),null,net.minecraft.world.InteractionHand.MAIN_HAND,false);h.assertTrue(logic.ports.get(0).filters[0].equals(AEItemKey.of(Items.GOLD_INGOT)),"Modifier includes filters");player.setPos(player.getX()+30,player.getY(),player.getZ());h.assertFalse(com.mpp.aedialsworks.cells.network.CellsMemoryCards.interact(player,machine(h).cellsPos(),null,net.minecraft.world.InteractionHand.MAIN_HAND,true),"Out-of-reach replay rejected");h.succeed();
    }
    @GameTest(template="empty") public static void bucketMenuTransferAndMachineConversionPreservePayload(GameTestHelper h){
        h.setBlock(1,1,1,AWCells.BLOCKS.get(MachineKind.FLUID_IMPORT).get());var logic=(InterfaceLogic)machine(h).cellsLogic();var player=net.minecraftforge.common.util.FakePlayerFactory.get(h.getLevel(),new com.mojang.authlib.GameProfile(UUID.randomUUID(),"P3Buckets"));player.setGameMode(net.minecraft.world.level.GameType.SURVIVAL);var pos=machine(h).cellsPos();player.setPos(pos.getX(),pos.getY(),pos.getZ());var nonce=UUID.randomUUID();var menu=new com.mpp.aedialsworks.cells.menu.CellsMenu(83,player.getInventory(),machine(h),nonce);player.containerMenu=menu;var action=new CompoundTag();action.putUUID("session",nonce);action.putInt("port",0);action.putInt("slot",0);menu.setCarried(new ItemStack(Items.WATER_BUCKET));menu.receiveClientAction(player,com.mpp.aedialsworks.common.util.AWIds.id("cells_buffer"),action);h.assertTrue(menu.getCarried().is(Items.BUCKET)&&logic.ports.get(0).amounts[0]==1000,"Bucket deposits 1000 mB: valid="+menu.stillValid(player)+" build="+player.mayBuild()+" amount="+logic.ports.get(0).amounts[0]+" cursor="+menu.getCarried());menu.receiveClientAction(player,com.mpp.aedialsworks.common.util.AWIds.id("cells_buffer"),action);h.assertTrue(menu.getCarried().is(Items.WATER_BUCKET)&&logic.ports.get(0).amounts[0]==0,"Bucket withdraws exactly 1000 mB");player.containerMenu=player.inventoryMenu;
        var payload=new CompoundTag();payload.put("cells",logic.save());var input=new ItemStack(AWCells.BLOCK_ITEMS.get(MachineKind.FLUID_IMPORT).get());input.setTag(payload);var grid=frame();grid.setItem(0,input);var converted=h.getLevel().getRecipeManager().getRecipeFor(RecipeType.CRAFTING,grid,h.getLevel()).orElseThrow().assemble(grid,h.getLevel().registryAccess());h.assertTrue(converted.is(AWCells.PARTS.get(MachineKind.FLUID_IMPORT).get())&&payload.equals(converted.getTag()),"Block-to-part conversion preserves NBT");grid.setItem(1,new ItemStack(AWCells.BLOCK_ITEMS.get(MachineKind.IMPORT).get()));h.assertTrue(h.getLevel().getRecipeManager().getRecipeFor(RecipeType.CRAFTING,grid,h.getLevel()).isEmpty(),"Combined assembly rejects configured machine rather than deleting its state");h.succeed();
    }
    @GameTest(template="empty") public static void equalDistributionTagFiltersAndCommands(GameTestHelper h){
        var stack=new ItemStack(AWCells.cell(CellFamily.HD_ITEM,CellTier.K1).get());var item=(TieredCellItem)stack.getItem();item.getUpgrades(stack).setItemDirect(0,new ItemStack(AWCells.UPGRADES.get("equal_distribution_card_2x").get()));var cell=CellHandler.open(stack,null);long first=cell.insert(IRON,Long.MAX_VALUE,Actionable.MODULATE,SOURCE);long second=cell.insert(AEItemKey.of(Items.GOLD_INGOT),Long.MAX_VALUE,Actionable.MODULATE,SOURCE);h.assertTrue(first>0&&first==second&&cell.insert(AEItemKey.of(Items.DIRT),1,Actionable.MODULATE,SOURCE)==0,"Equal per-type quota and type limit");
        var tagged=new ItemStack(AWCells.cell(CellFamily.HD_ITEM,CellTier.K1).get());item.getUpgrades(tagged).setItemDirect(0,new ItemStack(AWCells.UPGRADES.get("tag_card").get()));tagged.getOrCreateTag().putString("filterTag","forge:ingots/iron");var filter=CellHandler.open(tagged,null);h.assertTrue(filter.insert(IRON,1,Actionable.SIMULATE,SOURCE)==1&&filter.insert(AEItemKey.of(Items.DIRT),1,Actionable.SIMULATE,SOURCE)==0,"Namespaced tag filter");
        var player=net.minecraftforge.common.util.FakePlayerFactory.get(h.getLevel(),new com.mojang.authlib.GameProfile(UUID.randomUUID(),"P3Commands"));player.getInventory().selected=0;player.getInventory().setItem(0,tagged);var source=player.createCommandSourceStack().withPermission(2).withSuppressedOutput();h.assertTrue(h.getLevel().getServer().getCommands().performPrefixedCommand(source,"fillcell item minecraft:iron_ingot 4294967296")==1&&count(CellHandler.open(tagged,null),IRON)==4294967296L,"Brigadier fill accepts long quantities");h.assertTrue(h.getLevel().getServer().getCommands().performPrefixedCommand(source,"inspectslot 0")==1,"Inspect command");h.succeed();
    }


    @GameTest(template="empty") public static void compressionCardsAndTagUnification(GameTestHelper h){
        var stack=new ItemStack(AWCells.cell(CellFamily.COMPACTING,CellTier.K1).get());var item=(TieredCellItem)stack.getItem();item.getConfigInventory(stack).setStack(0,new GenericStack(AEItemKey.of(Items.IRON_NUGGET),1));
        var cell=(CompactingCellState)CellHandler.open(stack,null);h.assertTrue(cell.insert(AEItemKey.of(Items.IRON_BLOCK),1,Actionable.SIMULATE,SOURCE)==0,"Default one upper tier");item.getUpgrades(stack).setItemDirect(0,new ItemStack(AWCells.UPGRADES.get("compression_tier_card_3x").get()));cell=(CompactingCellState)CellHandler.open(stack,null);h.assertTrue(cell.insert(AEItemKey.of(Items.IRON_BLOCK),2,Actionable.MODULATE,SOURCE)==2,"Two compression tiers are active");h.assertTrue(cell.extract(AEItemKey.of(Items.IRON_NUGGET),162,Actionable.MODULATE,SOURCE)==162,"Cross-tier exact extraction");
        item.getConfigInventory(stack).setStack(0,new GenericStack(AEItemKey.of(Items.IRON_BLOCK),1));item.getUpgrades(stack).setItemDirect(0,new ItemStack(AWCells.UPGRADES.get("decompression_tier_card_3x").get()));cell=(CompactingCellState)CellHandler.open(stack,null);h.assertTrue(cell.insert(AEItemKey.of(Items.IRON_NUGGET),82,Actionable.MODULATE,SOURCE)==82,"Two lower tiers are active");item.getUpgrades(stack).setItemDirect(0,ItemStack.EMPTY);cell=(CompactingCellState)CellHandler.open(stack,null);h.assertTrue(cell.extract(AEItemKey.of(Items.IRON_BLOCK),1,Actionable.MODULATE,SOURCE)==1&&cell.extract(AEItemKey.of(Items.IRON_NUGGET),1,Actionable.MODULATE,SOURCE)==1,"Downgrade retains indivisible remainder");
        var tagged=new ItemStack(AWCells.cell(CellFamily.COMPACTING,CellTier.K1).get());item.getConfigInventory(tagged).setStack(0,new GenericStack(IRON,1));var variant=new ItemStack(Items.IRON_INGOT);variant.setHoverName(net.minecraft.network.chat.Component.literal("Equivalent ingot"));h.assertTrue(CellHandler.open(tagged,null).insert(AEItemKey.of(variant),13,Actionable.SIMULATE,SOURCE)==0,"No implicit conversion");item.getUpgrades(tagged).setItemDirect(0,new ItemStack(AWCells.UPGRADES.get("tag_card").get()));tagged.getOrCreateTag().putString("filterTag","forge:ingots/iron");var unified=CellHandler.open(tagged,null);h.assertTrue(unified.insert(AEItemKey.of(variant),13,Actionable.MODULATE,SOURCE)==13&&unified.extract(IRON,13,Actionable.MODULATE,SOURCE)==13,"Explicit Tag card unifies to configured chain");h.succeed();
    }
    @GameTest(template="empty",timeoutTicks=150) public static void automaticPullRespectsKeepAndQuantity(GameTestHelper h){
        network(h,MachineKind.IMPORT);h.setBlock(0,1,1,net.minecraft.world.level.block.Blocks.CHEST);h.runAfterDelay(40,()->{var logic=(InterfaceLogic)machine(h).cellsLogic();var external=(net.minecraft.world.level.block.entity.ChestBlockEntity)h.getBlockEntity(new BlockPos(0,1,1));external.setItem(0,new ItemStack(Items.IRON_INGOT,20));logic.keepQuantity=5;logic.transferQuantity=10;logic.upgrades.setItemDirect(0,new ItemStack(AWCells.UPGRADES.get("pull_card").get()));logic.tick();h.assertTrue(external.getItem(0).getCount()==10&&logic.ports.get(0).amounts[0]==10,"Pull honors transfer amount");logic.tick();h.assertTrue(external.getItem(0).getCount()==10&&count(machine(h).getMainNode().getGrid().getStorageService().getInventory(),IRON)==10,"Pulled contents reach ME; same tick does not pull twice");h.runAfterDelay(2,()->{logic.tick();h.assertTrue(external.getItem(0).getCount()==5,"Keep floor remains in external chest");h.succeed();});});
    }
    @GameTest(template="empty",timeoutTicks=150) public static void automaticPushRespectsKeepAndQuantity(GameTestHelper h){
        network(h,MachineKind.EXPORT);h.setBlock(0,1,1,net.minecraft.world.level.block.Blocks.CHEST);h.runAfterDelay(40,()->{var logic=(InterfaceLogic)machine(h).cellsLogic();var external=(net.minecraft.world.level.block.entity.ChestBlockEntity)h.getBlockEntity(new BlockPos(0,1,1));machine(h).getMainNode().getGrid().getStorageService().getInventory().insert(IRON,32,Actionable.MODULATE,SOURCE);logic.ports.get(0).filters[0]=IRON;logic.keepQuantity=5;logic.transferQuantity=10;logic.upgrades.setItemDirect(0,new ItemStack(AWCells.UPGRADES.get("push_card").get()));logic.tick();h.assertTrue(external.getItem(0).getCount()==10&&logic.ports.get(0).amounts[0]==22,"Push moves requested amount and conserves buffer");logic.keepQuantity=22;h.runAfterDelay(2,()->{logic.tick();h.assertTrue(external.getItem(0).getCount()==10&&logic.ports.get(0).amounts[0]==22,"Push honors keep floor");h.succeed();});});
    }


    @GameTest(template="empty",timeoutTicks=240) public static void parallelProxyPriorityFuzzyAndCycle(GameTestHelper h){
        h.setBlock(1,1,1,AEBlocks.DRIVE.block());h.setBlock(1,0,1,AEBlocks.CREATIVE_ENERGY_CELL.block());h.setBlock(4,0,1,AEBlocks.CREATIVE_ENERGY_CELL.block());
        var drive=(DriveBlockEntity)h.getBlockEntity(new BlockPos(1,1,1));drive.getInternalInventory().setItemDirect(0,AEItems.ITEM_CELL_64K.stack());
        var backs=new CellsPart[2];var fronts=new CellsPart[2];var reverse=new CellsPart[2];
        for(int i=0;i<2;i++){backs[i]=PartHelper.setPart(h.getLevel(),h.absolutePos(new BlockPos(2,1,1+i*2)),Direction.EAST,h.makeMockPlayer(),AWCells.PARTS.get(MachineKind.PROXY_BACK).get());fronts[i]=PartHelper.setPart(h.getLevel(),h.absolutePos(new BlockPos(3,1,1+i*2)),Direction.WEST,h.makeMockPlayer(),AWCells.PARTS.get(MachineKind.PROXY_FRONT).get());}
        h.runAfterDelay(30,()->{var power=(appeng.me.helpers.IGridConnectedBlockEntity)h.getBlockEntity(new BlockPos(4,0,1));for(int i=0;i<2;i++){if(backs[i].getGridNode().getGrid()!=drive.getMainNode().getGrid())GridHelper.createConnection(backs[i].getGridNode(),drive.getMainNode().getNode());if(fronts[i].getGridNode().getGrid()!=power.getMainNode().getGrid())GridHelper.createConnection(fronts[i].getGridNode(),power.getMainNode().getNode());}});
        h.runAfterDelay(85,()->{var a=(ProxyLogic)fronts[0].logic;var b=(ProxyLogic)fronts[1].logic;var origin=drive.getMainNode().getGrid().getStorageService().getInventory();origin.insert(IRON,120,Actionable.MODULATE,SOURCE);a.priority=10;b.priority=20;
            h.assertTrue(count(a.storageView(),IRON)==0&&count(b.storageView(),IRON)==120,"Only higher priority parallel proxy lists physical inventory");a.priority=30;h.assertTrue(count(a.storageView(),IRON)==120&&count(b.storageView(),IRON)==0,"Priority handover has no double counting");
            var named=new ItemStack(Items.IRON_INGOT);named.setHoverName(net.minecraft.network.chat.Component.literal("Named variant"));var key=AEItemKey.of(named);origin.insert(key,9,Actionable.MODULATE,SOURCE);a.filters.setStack(0,new GenericStack(IRON,1));h.assertTrue(count(a.storageView(),key)==0,"Exact filter rejects NBT variant");a.upgrades.setItemDirect(0,AEItems.FUZZY_CARD.stack());h.assertTrue(count(a.storageView(),key)==9,"Fuzzy card exposes matching variant");a.items=false;h.assertTrue(count(a.storageView(),IRON)==0,"Channel disable applies to proxy view");a.items=true;
            reverse[0]=PartHelper.setPart(h.getLevel(),h.absolutePos(new BlockPos(2,1,2)),Direction.EAST,h.makeMockPlayer(),AWCells.PARTS.get(MachineKind.PROXY_FRONT).get());reverse[1]=PartHelper.setPart(h.getLevel(),h.absolutePos(new BlockPos(3,1,2)),Direction.WEST,h.makeMockPlayer(),AWCells.PARTS.get(MachineKind.PROXY_BACK).get());
        });
        h.runAfterDelay(115,()->{GridHelper.createConnection(reverse[0].getGridNode(),backs[0].getGridNode());GridHelper.createConnection(reverse[1].getGridNode(),fronts[0].getGridNode());});
        h.runAfterDelay(175,()->{for(var part:List.of(fronts[0],fronts[1],reverse[0])){var proxy=(ProxyLogic)part.logic;h.assertTrue(proxy.guardStatus().equals("CYCLE")&&count(proxy.storageView(),IRON)==0,"Real two-network cycle closes all views: "+proxy.guardStatus());}h.succeed();});
    }

    @GameTest(template="empty") public static void proxyTickBoundsAndConfiguredUpgradeCapacity(GameTestHelper h){
        var config=com.mpp.aedialsworks.common.config.AWConfigs.SERVER.cells.general;
        int oldMin=config.subnetProxyMinTickRate.get(),oldMax=config.subnetProxyMaxTickRate.get(),oldSlots=config.subnetProxyUpgradeSlots.get(),oldCellSlots=config.hdItemCellUpgradeSlots.get();
        try{
            config.subnetProxyMinTickRate.set(37);config.subnetProxyMaxTickRate.set(11);config.subnetProxyUpgradeSlots.set(24);config.hdItemCellUpgradeSlots.set(16);
            var part=AWCells.PARTS.get(MachineKind.PROXY_FRONT).get().createPart();var proxy=(ProxyLogic)part.logic;var request=proxy.getTickingRequest(null);
            h.assertTrue(request.minTickRate()==37&&request.maxTickRate()==37&&request.initialTickRate()==37,"Inverted tick bounds are normalized");
            h.assertTrue(proxy.upgrades.size()==24,"Configured proxy upgrade slots");
            config.subnetProxyMaxTickRate.set(120);request=proxy.getTickingRequest(null);h.assertTrue(request.maxTickRate()==120,"Configured maximum tick interval is applied");
            var item=AWCells.cell(CellFamily.HD_ITEM,CellTier.K1).get();h.assertTrue(item.getUpgrades(new ItemStack(item)).size()==16,"Configured cell upgrade slots");
        }finally{config.subnetProxyMinTickRate.set(oldMin);config.subnetProxyMaxTickRate.set(oldMax);config.subnetProxyUpgradeSlots.set(oldSlots);config.hdItemCellUpgradeSlots.set(oldCellSlots);}
        h.succeed();
    }

}
